// Generated by CoffeeScript 1.12.6
(function() {
  var foo,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  foo = null;

  define(function(require, exports, module) {
    var Autocomplete, BiblioCompleter, BiblioFilesCompleter, DEFAULT_META_SCORE, DEFAULT_SCORE, LatexParsingContext, lang, util;
    LatexParsingContext = require("ace/ext/papeeria/latex_parsing_context");
    Autocomplete = require("ace/autocomplete");
    util = require("ace/autocomplete/util");
    lang = require("../../lib/lang");
    BiblioFilesCompleter = (function(superClass) {
      extend(BiblioFilesCompleter, superClass);

      function BiblioFilesCompleter(createCallback, insertCallback, createLabel) {
        this.createCallback = createCallback;
        this.insertCallback = insertCallback;
        this.createLabel = createLabel;
        this.detach = bind(this.detach, this);
        this.changeListener = bind(this.changeListener, this);
        this.insertMatch = bind(this.insertMatch, this);
        this.updateCompletions = bind(this.updateCompletions, this);
        this._doCreate = bind(this._doCreate, this);
        this._doInsert = bind(this._doInsert, this);
        this._setCompletions = bind(this._setCompletions, this);
        this.setFiles = bind(this.setFiles, this);
        BiblioFilesCompleter.__super__.constructor.call(this);
      }

      BiblioFilesCompleter.prototype.setFiles = function(files) {
        return this.files = files;
      };

      BiblioFilesCompleter.prototype._setCompletions = function() {
        var matches;
        matches = this.files.map((function(_this) {
          return function(file) {
            return {
              name: file.name,
              meta: file.path,
              action: function() {
                return _this._doInsert(file);
              }
            };
          };
        })(this));
        matches.push({
          name: this.createLabel,
          meta: "",
          action: (function(_this) {
            return function() {
              return _this._doCreate();
            };
          })(this)
        });
        return this.completions = new Autocomplete.FilteredList(matches);
      };

      BiblioFilesCompleter.prototype._doInsert = function(file) {
        if (typeof this.insertCallback === "function") {
          this.insertCallback(file);
        }
        return this.detach();
      };

      BiblioFilesCompleter.prototype._doCreate = function() {
        return typeof this.createCallback === "function" ? this.createCallback(((function(_this) {
          return function() {
            return _this.editor.completer = null;
          };
        })(this)), this._doInsert) : void 0;
      };

      BiblioFilesCompleter.prototype.updateCompletions = function(keepPopupPosition) {
        var prefix;
        this._setCompletions();
        prefix = util.getCompletionPrefix(this.editor);
        return this.openPopup(this.editor, prefix, keepPopupPosition);
      };

      BiblioFilesCompleter.prototype.insertMatch = function(editor, data) {
        if (data == null) {
          data = this.popup.getData(this.popup.getRow());
        }
        if ((data == null) || (data.action == null)) {
          this.detach();
          return;
        }
        return data.action();
      };

      BiblioFilesCompleter.prototype.changeListener = function() {
        return this.detach();
      };

      BiblioFilesCompleter.prototype.detach = function() {
        this.editor.completer = new Autocomplete.Autocomplete();
        return BiblioFilesCompleter.__super__.detach.call(this);
      };

      return BiblioFilesCompleter;

    })(Autocomplete.Autocomplete);
    DEFAULT_SCORE = 1000;
    DEFAULT_META_SCORE = 10;
    BiblioCompleter = (function() {
      function BiblioCompleter(isMendeleyEnabled, searchLabel, importLabel, importSource, searchCallback) {
        this.isMendeleyEnabled = isMendeleyEnabled;
        this.searchLabel = searchLabel;
        this.importLabel = importLabel;
        this.importSource = importSource;
        this.searchCallback = searchCallback;
        this.insertMatch = bind(this.insertMatch, this);
        this._doSearch = bind(this._doSearch, this);
        this.setImportCallback = bind(this.setImportCallback, this);
        this.getCompletions = bind(this.getCompletions, this);
        ({});
      }

      BiblioCompleter.prototype.getCompletions = function(editor, session, pos, prefix, callback) {
        var defaultResult, token;
        token = session.getTokenAt(pos.row, pos.column);
        if (LatexParsingContext.isType(token, "cite")) {
          defaultResult = [
            {
              name: this.searchLabel,
              snippet: this.searchLabel + prefix,
              meta: "",
              score: DEFAULT_SCORE,
              meta_score: DEFAULT_META_SCORE,
              completer: this,
              action: (function(_this) {
                return function(editor) {
                  return _this._doSearch(editor);
                };
              })(this)
            }
          ];
          if (this.isMendeleyEnabled != null) {
            defaultResult.push({
              name: this.importLabel,
              snippet: this.importLabel + prefix,
              meta: this.importSource,
              score: DEFAULT_SCORE,
              meta_score: DEFAULT_META_SCORE,
              completer: this,
              action: (function(_this) {
                return function(editor) {
                  return typeof _this.importCallback === "function" ? _this.importCallback() : void 0;
                };
              })(this)
            });
          }
          callback(null, defaultResult);
          return;
        }
        callback(null, []);
      };

      BiblioCompleter.prototype.setImportCallback = function(callback) {
        return this.importCallback = callback;
      };

      BiblioCompleter.prototype._doSearch = function(editor) {
        var prefix;
        prefix = util.getCompletionPrefix(editor);
        return typeof this.searchCallback === "function" ? this.searchCallback({
          query: prefix,
          insertCallback: (function(_this) {
            return function(completer) {
              return completer != null ? completer.showPopup(editor) : void 0;
            };
          })(this)
        }) : void 0;
      };

      BiblioCompleter.prototype.insertMatch = function(editor, data) {
        editor.completer.detach();
        editor.completer = null;
        if ((data != null) && (data.action != null)) {
          return data.action(editor);
        }
      };

      return BiblioCompleter;

    })();
    return {
      BiblioCompleter: BiblioCompleter,
      BiblioFilesCompleter: BiblioFilesCompleter
    };
  });

}).call(this);
