// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    var EQUATION_STATE, LIST_STATE, PapeeriaLatexHighlightRules, getContext, getNestingOfList;
    PapeeriaLatexHighlightRules = require('./papeeria_latex_highlight_rules');
    EQUATION_STATE = PapeeriaLatexHighlightRules.EQUATION_STATE;
    LIST_STATE = PapeeriaLatexHighlightRules.LIST_STATE;

    /*
     * @param {Number} row
     * 
     * Returns context at row.
     */
    getContext = function(session, row) {
      var states;
      states = session.getState(row);
      if (Array.isArray(states)) {
        return states[states.length - 1];
      } else {
        return states;
      }
    };
    getNestingOfList = function(session, row) {
      var arrayLength, count, i, states;
      states = session.getState(row);
      count = 0;
      arrayLength = states.length;
      i = arrayLength - 1;
      while (i >= 0 && states[i] === LIST_STATE) {
        i--;
        count++;
      }
      return count;
    };
    return exports.ContextHelper = {
      getContext: getContext,
      getNestingOfList: getNestingOfList
    };
  });

}).call(this);
