// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    var Range, findSurroundingBrackets, highlightBrackets, highlightInitBind;
    Range = require("ace/range").Range;
    highlightBrackets = function(editor) {
      var pos, range, rangeLeft, rangeRight, session;
      pos = findSurroundingBrackets(editor);
      session = editor.getSession();
      if (session.$bracketHighlightRight || session.$bracketHighlightLeft) {
        session.removeMarker(session.$bracketHighlightLeft);
        session.removeMarker(session.$bracketHighlightRight);
        session.$bracketHighlightLeft = null;
        session.$bracketHighlightRight = null;
        return;
      }
      if (!pos.mismatch) {
        rangeLeft = new Range(pos.left.row, pos.left.column, pos.left.row, pos.left.column + 1);
        rangeRight = new Range(pos.right.row, pos.right.column, pos.right.row, pos.right.column + 1);
        session.$bracketHighlightLeft = session.addMarker(rangeLeft, "ace_bracket", "text");
        session.$bracketHighlightRight = session.addMarker(rangeRight, "ace_bracket", "text");
      } else {
        if (pos.left && pos.right) {
          range = new Range(pos.left.row, pos.left.column, pos.right.row, pos.right.column + 1);
          session.$bracketHighlightLeft = session.addMarker(range, "ace_error-marker", "text");
        }
        if (pos.left && !pos.right) {
          rangeLeft = new Range(pos.left.row, pos.left.column, Infinity, Infinity);
          session.$bracketHighlightLeft = session.addMarker(rangeLeft, "ace_error-marker", "text");
        }
        if (pos.right && !pos.left) {
          rangeRight = new Range(0, 0, pos.right.row, pos.right.column + 1);
          session.$bracketHighlightRight = session.addMarker(rangeRight, "ace_error-marker", "text");
        }
      }
      session.$positionOfHighlight = pos;
    };
    findSurroundingBrackets = function(editor) {
      var allBrackets, expectedRightBracket, key, leftCandidate, leftNearest, positionLeftwards, positionRightwards, result, rightBracket, rightCandidate, rightNearest, session;
      positionRightwards = editor.getCursorPosition();
      positionLeftwards = editor.getCursorPosition();
      positionLeftwards.column += 1;
      session = editor.getSession();
      allBrackets = {
        left: [session.$findOpeningBracket('}', positionLeftwards, /(\.?.paren)+/), session.$findOpeningBracket(']', positionLeftwards, /(\.?.paren)+/), session.$findOpeningBracket(')', positionLeftwards, /(\.?.paren)+/)],
        right: [session.$findClosingBracket('{', positionRightwards, /(\.?.paren)+/), session.$findClosingBracket('[', positionRightwards, /(\.?.paren)+/), session.$findClosingBracket('(', positionRightwards, /(\.?.paren)+/)]
      };
      leftNearest = null;
      rightNearest = null;
      key = 0;
      while (key < allBrackets.left.length) {
        leftCandidate = allBrackets.left[key];
        rightCandidate = allBrackets.right[key];
        if (!leftNearest) {
          leftNearest = leftCandidate;
        }
        if (!rightNearest) {
          rightNearest = rightCandidate;
        }
        if (leftCandidate) {
          if (leftNearest.row <= leftCandidate.row) {
            if (leftNearest.row === leftCandidate.row) {
              if (leftNearest.column < leftCandidate.column) {
                leftNearest = leftCandidate;
              }
            } else {
              leftNearest = leftCandidate;
            }
          }
        }
        if (rightCandidate) {
          if (rightNearest.row >= rightCandidate.row) {
            if (rightNearest.row === rightCandidate.row) {
              if (rightNearest.column > rightCandidate.column) {
                rightNearest = rightCandidate;
              }
            } else {
              rightNearest = rightCandidate;
            }
          }
        }
        key++;
      }
      result = {
        left: leftNearest,
        right: rightNearest,
        mismatch: true,
        equals: function(object) {
          if (object.left !== this.left) {
            return false;
          }
          if (object.right !== this.right) {
            return false;
          }
          if (object.mismatch !== this.mismatch) {
            return false;
          }
          return true;
        }
      };
      if (result.left && result.right) {
        expectedRightBracket = session.$brackets[session.getLine(result.left.row).charAt(result.left.column)];
        rightBracket = session.getLine(result.right.row).charAt(result.right.column);
        if (expectedRightBracket === rightBracket) {
          result.mismatch = false;
        }
      }
      return result;
    };
    highlightInitBind = function(editor, bindKey) {
      var isOutFromAreaOfHighlight, keyboardHandler, session;
      session = editor.getSession();
      keyboardHandler = {
        name: 'highlightBrackets',
        bindKey: bindKey,
        exec: function(editor) {
          return highlightBrackets(editor);
        },
        readOnly: true
      };
      editor.commands.addCommand(keyboardHandler);
      session.getSelection().on("changeCursor", function() {
        if (session.$bracketHighlightLeft || session.$bracketHighlightRight) {
          session.removeMarker(session.$bracketHighlightLeft);
          session.removeMarker(session.$bracketHighlightRight);
          session.$bracketHighlightLeft = null;
          session.$bracketHighlightRight = null;
          if (!isOutFromAreaOfHighlight()) {
            highlightBrackets(editor);
          }
        }
      });
      isOutFromAreaOfHighlight = function() {
        var newPosition, oldPosition;
        oldPosition = session.$positionOfHighlight;
        newPosition = findSurroundingBrackets(editor);
        return oldPosition.equals(newPosition);
      };
    };
    return exports.highlighter = {
      highlightBrackets: highlightBrackets,
      findSurroundingBrackets: findSurroundingBrackets,
      highlightInitBind: highlightInitBind
    };
  });

}).call(this);
