// Generated by CoffeeScript 1.10.0
(function() {
  var foo;

  foo = null;

  define(function(require, exports, module) {
    var EQUATION_STATE, EQUATION_TOKEN_TYPE, LIST_STATE, LIST_TOKEN_TYPE, PapeeriaLatexHighlightRules, getContext, getContextFromRow, isType;
    PapeeriaLatexHighlightRules = require("ace/ext/papeeria/papeeria_latex_highlight_rules");
    EQUATION_STATE = "equation";
    LIST_STATE = "list";
    EQUATION_TOKEN_TYPE = PapeeriaLatexHighlightRules.EQUATION_TOKEN_TYPE;
    LIST_TOKEN_TYPE = PapeeriaLatexHighlightRules.LIST_TOKEN_TYPE;
    isType = function(token, type) {
      return token.type.split(".").indexOf(type) > -1;
    };

    /*
     * @param {(number, number) pos}
     *
     * Returns context at cursor position.
     */
    getContext = function(session, row, column) {
      var state, token;
      state = getContextFromRow(session, row);
      token = session.getTokenAt(row, column);
      if (token != null) {
        if (isType(token, EQUATION_TOKEN_TYPE)) {
          return EQUATION_STATE;
        }
        if (isType(token, LIST_TOKEN_TYPE)) {
          return LIST_STATE;
        }
      }
      return state;
    };
    getContextFromRow = function(session, row) {
      var states;
      states = session.getState(row);
      if (Array.isArray(states)) {
        return states[states.length - 1];
      } else {
        return states;
      }
    };
    exports.getContext = getContext;
    exports.isType = isType;
  });

}).call(this);
