// Generated by CoffeeScript 1.10.0
(function() {
  var foo;

  foo = null;

  define(function(require, exports, module) {
    var EQUATION_STATE, EQUATION_TOKENTYPE, LIST_STATE, LIST_TOKENTYPE, PapeeriaLatexHighlightRules, getContext, getContextFromRow, isType;
    PapeeriaLatexHighlightRules = require("ace/ext/papeeria/papeeria_latex_highlight_rules");
    EQUATION_STATE = PapeeriaLatexHighlightRules.EQUATION_STATE;
    LIST_STATE = PapeeriaLatexHighlightRules.LIST_STATE;
    EQUATION_TOKENTYPE = PapeeriaLatexHighlightRules.EQUATION_TOKENTYPE;
    LIST_TOKENTYPE = PapeeriaLatexHighlightRules.LIST_TOKENTYPE;

    /*
     * @param {Number} row
     *
     * Returns context at row.
     */
    isType = function(token, type) {
      return token.type.split(".").indexOf(type) > -1;
    };
    getContext = function(session, row, column) {
      var state, token;
      state = getContextFromRow(session, row);
      token = session.getTokenAt(row, column);
      if (token != null) {
        if (isType(token, EQUATION_TOKENTYPE)) {
          return EQUATION_STATE;
        }
        if (isType(token, LIST_TOKENTYPE)) {
          return LIST_STATE;
        }
        return state;
      }
      return state;
    };
    getContextFromRow = function(session, row) {
      var states;
      states = session.getState(row);
      if (Array.isArray(states)) {
        return states[states.length - 1];
      } else {
        return states;
      }
    };
    exports.getContext = getContext;
    exports.isType = isType;
  });

}).call(this);
