// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    var PopoverHandler;
    return PopoverHandler = (function() {
      function PopoverHandler() {}

      PopoverHandler.prototype.show = function(jqPopoverContainer, options) {
        var popoverPosition;
        popoverPosition = jqPopoverContainer.position();
        popoverPosition.top += 24;
        jqPopoverContainer.css(popoverPosition);
        jqPopoverContainer.popover(options);
        jqPopoverContainer.popover("show");
      };

      PopoverHandler.prototype.hide = function(jqPopoverContainer) {
        return jqPopoverContainer.popover("destroy");
      };

      return PopoverHandler;

    })();
  });

}).call(this);
