// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    return {
      show: function(jqPopoverContainer, options) {
        var popoverPosition;
        jqPopoverContainer.css($("textarea.ace_text-input").position());
        popoverPosition = jqPopoverContainer.position();
        popoverPosition.top += 24;
        jqPopoverContainer.css(popoverPosition);
        jqPopoverContainer.popover(options);
        jqPopoverContainer.popover("show");
      },
      hide: function(jqPopoverContainer) {
        return jqPopoverContainer.popover("destroy");
      }
    };
  });

}).call(this);
