// Generated by CoffeeScript 1.10.0
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function(require, exports, module) {
    var NUMERIC_REGEXP, SpellChecker;
    NUMERIC_REGEXP = /^\d+$/;
    SpellChecker = (function() {
      function SpellChecker() {
        this.check = bind(this.check, this);
      }

      SpellChecker.prototype.check = function(token) {
        return !NUMERIC_REGEXP.test(token);
      };

      return SpellChecker;

    })();
    exports.SpellChecker = SpellChecker;
  });

}).call(this);

//# sourceMappingURL=spellchecker.js.map
