// Generated by CoffeeScript 1.11.1
(function() {
  var foo,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  foo = null;

  define(function(require, exports, module) {

    /*
    Few types used in this module:
    
    Correction
      caption: string
      value: string
      meta: string
      score: number
      actionId?: string
    
    PopupAction
      id: string
      asCorrection(): Correction
      doAction(word: string)
    
    PopupActionManager
       * Decide which action should respond to given word and return it
      actionForWord(word: string): PopupAction
    
       * Return action corresponding for given correction if any (or null)
      actionForCorrection(correction: Correction): PopupAction
     */
    var Autocomplete, Spellchecker, SpellcheckerCompleter, convertCorrectionList, extractWord, getCurrentWordRange, mySpellcheckerPopup, setup;
    Autocomplete = require('ace/autocomplete');
    Spellchecker = require('ace/ext/papeeria/spellchecker');

    /*
    Returns Range object that describes the current word position.
    @param {Editor} editor: editor object.
    @return {Range}: current word range.
     */
    getCurrentWordRange = function(editor) {
      var col, row, session;
      session = editor.getSession();
      row = editor.getCursorPosition().row;
      col = editor.getCursorPosition().column;
      return session.getWordRange(row, col);
    };

    /*
    Convert an array of string to popup-eligible structure.
    @param {PopupAction} action -- action object to be prepended to the resulting list (or null)
    @param {Array<String>} corrections -- array of corrections
    @return {Array<Correction>}
     */
    convertCorrectionList = function(action, corrections) {
      var i, item, list;
      list = (function() {
        var j, len, results;
        results = [];
        for (i = j = 0, len = corrections.length; j < len; i = ++j) {
          item = corrections[i];
          results.push({
            caption: item,
            value: item,
            meta: "",
            score: corrections.length - i
          });
        }
        return results;
      })();
      if (action) {
        list.unshift(action.asCorrection());
      }
      return list;
    };

    /*
    Get the word under the cursor.
    @param {Editor} editor: editor object.
    @return {String}: the current word.
     */
    extractWord = function(editor) {
      var session, wordRange;
      session = editor.getSession();
      wordRange = getCurrentWordRange(editor);
      return session.getTextRange(wordRange);
    };
    mySpellcheckerPopup = null;

    /*
    Sets up spellchecker popup and implements some routines
    to work on current in the editor.
    @param {Editor} editor -- ace editor
    @param {(String, String) -> void} onReplaced -- callback taking typo and replacement
    @param {PopupActionManager} actionManager -- autocomplete actions manager
     */
    setup = function(editor, onReplaced, actionManager) {
      var command;
      mySpellcheckerPopup = new SpellcheckerCompleter(onReplaced, actionManager);
      command = {
        name: "spellCheckPopup",
        exec: function() {
          editor.completer = mySpellcheckerPopup;
          return editor.completer.showPopup(editor);
        },
        bindKey: "Alt-Enter"
      };
      return editor.commands.addCommand(command);
    };
    SpellcheckerCompleter = (function(superClass) {
      extend(SpellcheckerCompleter, superClass);

      function SpellcheckerCompleter(onReplaced1, actionManager1) {
        this.onReplaced = onReplaced1;
        this.actionManager = actionManager1;
        this.insertMatch = bind(this.insertMatch, this);
        this.gatherCompletions = bind(this.gatherCompletions, this);
        this.isDisposable = true;
        SpellcheckerCompleter.__super__.constructor.call(this);
      }

      SpellcheckerCompleter.prototype.gatherCompletions = function(editor, callback) {
        var action, position, session, word;
        session = editor.getSession();
        position = editor.getCursorPosition();
        this.base = session.doc.createAnchor(position.row, position.column);
        word = extractWord(editor);
        action = this.actionManager.actionForWord(word);
        Spellchecker.getInstance().getCorrections(word, function(correctionsList) {
          return callback(null, {
            prefix: "",
            matches: convertCorrectionList(action, correctionsList),
            finished: true
          });
        });
        return true;
      };

      SpellcheckerCompleter.prototype.insertMatch = function(data, options) {
        var action, replacement, typo, wordRange;
        if (data == null) {
          data = this.popup.getData(this.popup.getRow());
        }
        action = this.actionManager.actionForCorrection(data);
        wordRange = getCurrentWordRange(this.editor);
        typo = this.editor.getSession().getTextRange(wordRange);
        if (action) {
          action.doAction(typo);
        } else {
          replacement = data.value || data;
          this.editor.getSession().replace(wordRange, replacement);
          this.onReplaced(typo, replacement);
        }
        return this.detach();
      };

      return SpellcheckerCompleter;

    })(Autocomplete.Autocomplete);
    return {
      setup: setup
    };
  });

}).call(this);
