// Generated by CoffeeScript 1.10.0
(function() {
  define(function(require, exports, module) {
    var equationKeywords, listKeywords;
    equationKeywords = ['\\alpha'];
    listKeywords = ['\\item'];
    exports.getCompletions = function(editor, session, pos, prefix, callback) {
      var context;
      context = session.getContext(pos.row);
      if (context === 'list') {
        callback(null, wordList.map(function(word) {
          return {
            caption: word,
            value: word,
            meta: 'list'
          };
        }));
      }
      if (context === "equation") {
        return callback(null, equationKeywords.map(function(word) {
          return {
            caption: word,
            value: word,
            meta: 'equation'
          };
        }));
      }
    };
  });

}).call(this);
