// Generated by CoffeeScript 1.12.6
(function() {
  define(function(require, exports, module) {
    var isType;
    exports.isType = isType = function(token, type) {
      return token.type.indexOf(type) > -1;
    };
  });

}).call(this);

//# sourceMappingURL=util.js.map
